### ISSUE TITLE
Add "Completed Successfully" to Upload/Sync/Copy/Move Commands

### ISSUE THREAD

**Issue by juklucas** [DataBiosphere/ssds#117]
It would be nice to notify the user when an upload or sync has completed successfully. This would allow the user to grep for the notification -- as opposed to looking through the stderr/stdout. It may also help us to troubleshoot with uploading teams.

Ideally this message would be present on all multi-file operations performed by ssds.

This message would likely be at "log level" INFO.

**Comment by xbrianh** [comment]
closed via #171
