### ISSUE TITLE
Increment Version Of SSDS

### ISSUE THREAD

**Issue by juklucas** [DataBiosphere/ssds#146]
When I execute:
`pip3 show ssds`

I get:
`Name: ssds
Version: 0.0.0`

It would be nice to increment versions -- so I can check which version I have installed on various VM's that I'm running.

**Comment by xbrianh** [comment]
The current version of the ssds will now show v0.0.1

This will be incremented as warranted by bug fixes, feature updates, and API changes.

Note that a specific version of the ssds may be installed with:
```
pip install git+https://github.com/DataBiosphere/ssds@v0.0.1
```

**Comment by xbrianh** [comment]
We may consider adding SSDS to the python package index.
